# fly.toml app configuration file generated for skillserver-test on 2024-04-28T15:22:21+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'skillserver-test'
primary_region = 'nrt'

[build]
  image = 'inspirit941/glide-api-test'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
